<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HidWizards.UCR</RootNamespace>
    <AssemblyName>UCR</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationIcon>UCR.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="1.1.2" />
    <PackageReference Include="MaterialDesignThemes" Version="2.5.1" />
    <PackageReference Include="RestSharp" Version="105.2.3" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="System.Management" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UCR.Core\UCR.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Remove="SampleData\**\*.xaml" />
    <DesignData Include="SampleData\**\*.xaml" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="UCR.ico" />
    <Resource Include="Resources\icon.png" />
    <Resource Include="Resources\UCR_24.png" />
  </ItemGroup>

  <Target Name="PreBuild" BeforeTargets="PreBuildEvent">
    <Exec Command="if exist &quot;$(SolutionDir)dependencies\Providers&quot; xcopy /Y /S /i &quot;$(SolutionDir)dependencies\Providers&quot; &quot;$(TargetDir)Providers&quot;" />
  </Target>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if exist &quot;$(SolutionDir)UCR.FileHandler\bin\$(ConfigurationName)\net8.0-windows\&quot; xcopy /Y /S /i &quot;$(SolutionDir)UCR.FileHandler\bin\$(ConfigurationName)\net8.0-windows\*.exe&quot; &quot;$(TargetDir)&quot;&#xD;&#xA;if exist &quot;$(SolutionDir)UCR.FileHandler\bin\$(ConfigurationName)\net8.0-windows\&quot; xcopy /Y /S /i &quot;$(SolutionDir)UCR.FileHandler\bin\$(ConfigurationName)\net8.0-windows\*.dll&quot; &quot;$(TargetDir)&quot;" />
  </Target>
</Project>