<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>UCR.FileHandler</RootNamespace>
    <AssemblyName>UCR_unblocker</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Trinet.Core.IO.Ntfs" Version="4.1.1" />
  </ItemGroup>
</Project>