<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>HidWizards.UCR.Plugins</RootNamespace>
    <AssemblyName>UCR.Plugins</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UCR.Core\UCR.Core.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="if not exist &quot;$(SolutionDir)UCR\bin\$(ConfigurationName)\net8.0-windows\Plugins\$(TargetName)&quot; mkdir &quot;$(SolutionDir)UCR\bin\$(ConfigurationName)\net8.0-windows\Plugins\$(TargetName)&quot;&#xD;&#xA;copy &quot;$(TargetPath)&quot; &quot;$(SolutionDir)UCR\bin\$(ConfigurationName)\net8.0-windows\Plugins\$(TargetName)\$(TargetName).dll&quot;&#xD;&#xA;if $(ConfigurationName) == Debug copy &quot;$(TargetDir)$(TargetName).pdb&quot; &quot;$(SolutionDir)UCR\bin\$(ConfigurationName)\net8.0-windows\Plugins\$(TargetName)\$(TargetName).pdb&quot;" />
  </Target>
</Project>