<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <RootNamespace>HidWizards.UCR.Core</RootNamespace>
    <AssemblyName>UCR.Core</AssemblyName>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>SYSLIB0011</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="NLog" Version="5.3.2" />
    <PackageReference Include="System.ComponentModel.Composition" Version="8.0.0" />
    <PackageReference Include="Mono.Options" Version="6.12.0.148" />
    <PackageReference Include="Trinet.Core.IO.Ntfs" Version="4.1.1" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IOWrapper.Core">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.Core.dll</HintPath>
    </Reference>
    <Reference Include="IOWrapper.DTOs">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.DTOs.dll</HintPath>
    </Reference>
    <Reference Include="IOWrapper.IProvider">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.IProvider.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Content Include="NLog.config">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

</Project>