<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <IsPackable>false</IsPackable>
    <RootNamespace>HidWizards.UCR.Tests</RootNamespace>
    <AssemblyName>UCR.Tests</AssemblyName>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.14.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.5.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.9.0" />
    <PackageReference Include="MaterialDesignColors" Version="1.1.2" />
    <PackageReference Include="MaterialDesignThemes" Version="2.5.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\UCR.Core\UCR.Core.csproj" />
    <ProjectReference Include="..\UCR.Plugins\UCR.Plugins.csproj" />
    <ProjectReference Include="..\UCR\UCR.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="IOWrapper.Core">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.Core.dll</HintPath>
    </Reference>
    <Reference Include="IOWrapper.DTOs">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.DTOs.dll</HintPath>
    </Reference>
    <Reference Include="IOWrapper.IProvider">
      <HintPath>..\dependencies\IOWrapper\IOWrapper.IProvider.dll</HintPath>
    </Reference>
  </ItemGroup>
</Project>